--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "SA"."USERS" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"USERNAME" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"HOBBY" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SA.USERS
SET DEFINE OFF;
Insert into SA.USERS (ID,USERNAME,PASSWORD,HOBBY) values (1,'admin','123admin','soccer');
Insert into SA.USERS (ID,USERNAME,PASSWORD,HOBBY) values (2,'sadmin','123sadmin','swimming');
Insert into SA.USERS (ID,USERNAME,PASSWORD,HOBBY) values (3,'tardmin','123tardmin','reading');
Insert into SA.USERS (ID,USERNAME,PASSWORD,HOBBY) values (4,'fatmin','123fatmin','driving');
Insert into SA.USERS (ID,USERNAME,PASSWORD,HOBBY) values (5,'madmin','123madmin','nothing');
--------------------------------------------------------
--  DDL for Index SYS_C008327
--------------------------------------------------------

  CREATE UNIQUE INDEX "SA"."SYS_C008327" ON "SA"."USERS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "SA"."USERS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SA"."USERS" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "SA"."USERS" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "SA"."USERS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
